---
title: xiaobei flingisland
email: jjzyjj@gmail.com
author: littlebadbay
author_github: littlebadbay
description: |
  a free world
baseurl: "/"
url: http://littlebadbay.github.io/
paginate: 12
github:
  user: littlebadbay
  repository: littlebadbay.github.com
  url: http://littlebadbay.github.io/
  status: true
home_bgfile: bg.jpg
sass:
  sass_dir: assets/css
  style: compressed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
gems:
- jekyll-paginate
exclude:
- vendor
