title: flying island
description: My Personal Blog
author: littlebadbay
logo: /static/img/avatar.png
github: https://github.com/littlebadbay
about: Freelance developer

baseurl: "http://littlebadbay.github.io"
url: "littlebadbay.github.io"

disqus_shortname: littlebadbay
google_analytics: UA-72862926-1

share:
  twitter_username: \#
  fb_appid: 000000000000


enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
